### ISSUE TITLE
Automated backups Crashing the server

### ISSUE THREAD

**Issue by telerez** [AriesLR/ALR-Palworld-Resources#2] opened 2024-01-26 03:51 UTC
I have been using your batch file for the last few days and started getting game crashes. 

Error Message:
From the palserver crash file:

**LowLevelFatalError [File:D:\works\repos\Pal_SVN\Pal-UE-App\Source\Pal\PalSaveGameManager.cpp] [Line: 359] Failed save to backup.**

I feel it is caused by the palserver executable trying to save the game at the same time its being zipped up and its causing an access conflict.

**Comment by AriesLR** [comment] 2024-01-27 00:41
Honestly, I discovered [WindowsGSM](https://windowsgsm.com) and haven't touched this too much lately, I realized there were much better options out there.

That being said I'll still check this out, although I personally never had any crashes while running it. I did however realize the backup is overwriting itself rather than creating multiple. I only realized that after making a lighter weight batch only for backups as the WindowsGSM backups save the entire server folder rather than only the save and config files.

**Comment by AriesLR** [comment] 2024-02-01 04:54
Issue _should_ be fixed now! I'm going to close this issue for now, but feel free to open another if you continue to encounter issues!

**Comment by AriesLR** [comment] 2024-02-01 06:46
After further testing it appears the issue is still happening. I'm not exactly sure how I can solve this, but it's something to look into. I will try some things and see if they work. I think you're probably right on why it's happening, but I'm not exactly sure how I'm going to solve it. Will look into it more in the morning.

**Comment by AriesLR** [comment] 2024-02-05 20:27
Going to wait a few more days before closing this, but it seems like after Palworld Version 0.1.4.0 the crashes have stopped on my end. It was very few to begin with maybe once every 2 days, but it hasn't happened for quite a few days now.

**Comment by AriesLR** [comment] 2024-02-07 19:45
Ugh. Crash today at 8:12 AM, Looks like its still happening just less frequently. Can't close this yet then as I'm still monitoring the issue.

**Comment by AriesLR** [comment] 2024-02-18 11:30
### Closing Issue

I'm dropping support for PDSL/PDSB as I'm working on a successor (I know it's a bit early for that, but I wanted to start over on this)

If you're still using this script, I recommend switching to [PalHub](https://github.com/AriesLR/PalHub), the successor to PDSL/PDSB.

**Closed by AriesLR** 2024-02-18 11:30 UTC
